# Generated by Django 3.0.4 on 2020-09-17 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='image',
            field=models.ImageField(blank=True, default='cats/cat2.jpg', upload_to=forum.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.CreateModel(
            name='SubAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, max_length=200, verbose_name='Текст ответа')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Answer', verbose_name='Комментарий')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Ответ на комментарий',
                'verbose_name_plural': 'Ответы на комментарии',
                'ordering': ['-date_of_creation'],
            },
        ),
    ]
