# Generated by Django 3.0.4 on 2020-09-05 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='text',
        ),
        migrations.AddField(
            model_name='advuser',
            name='image',
            field=models.ImageField(blank=True, default='cats/cat1.jpg', upload_to=forum.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
