# Generated by Django 3.0.4 on 2020-05-22 19:04

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=40, verbose_name='Название поста')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Краткое описание поста')),
                ('content', models.TextField(max_length=1000, verbose_name='Текст поста')),
                ('date_pub', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-date_pub'],
            },
        ),
    ]
