# Generated by Django 3.0.4 on 2020-05-27 19:56

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Краткое описание проекта')),
                ('content', models.TextField(blank=True, db_index=True, verbose_name='Описание проекта')),
                ('date_pub', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации проекта')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2000, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата публикации поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Краткое описание поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Название поста'),
        ),
    ]
