# Generated by Django 3.0.4 on 2020-05-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200527_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Ваше имя')),
                ('body', models.TextField(db_index=True, verbose_name='Ваше имя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
