# Generated by Django 3.0.4 on 2020-05-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200528_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Название статьи')),
                ('description', models.CharField(db_index=True, max_length=2000, verbose_name='Краткое описание статьи')),
                ('content', models.TextField(blank=True, db_index=True, verbose_name='Текст статьи')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'ordering': ['-date_pub'],
            },
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Фидбек', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='feedback',
            name='body',
            field=models.TextField(db_index=True, help_text="<span style='font-style:italic;'>Обязательно к заполнению</span>", verbose_name='Текст письма'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(db_index=True, help_text="<span style='font-style:italic;'>Обязательно к заполнению</span>", max_length=150, verbose_name='Ваше имя'),
        ),
    ]
