# Generated by Django 3.0.4 on 2020-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200531_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_pub'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(db_index=True, max_length=2000, verbose_name='Краткое описание статьи'),
        ),
    ]
