# Generated by Django 3.0.4 on 2020-06-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('RED', 'red'), ('DEFAULT', '#3ba2b9'), ('YELLOW', 'yellow'), ('GREEN', 'green'), ('GRAY', 'gray')], db_index=True, default='#3ba2b9', max_length=30, verbose_name='Цвет тэга'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Название тэга'),
        ),
    ]
