# Generated by Django 3.0.4 on 2020-06-22 14:31

from django.db import migrations, models
import main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200622_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.RemoveField(
            model_name='tag',
            name='master',
        ),
        migrations.AddField(
            model_name='tag',
            name='master',
            field=models.ManyToManyField(to='main.Post'),
        ),
    ]
