# Generated by Django 3.0.4 on 2020-06-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200622_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='master',
            field=models.ManyToManyField(to='main.Post'),
        ),
    ]
