# Generated by Django 3.0.4 on 2020-06-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200622_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='master',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='main.Tag'),
        ),
    ]
