# Generated by Django 3.0.4 on 2020-06-29 12:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200629_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=main.models.get_timestamp_path, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
