# Generated by Django 3.0.4 on 2020-06-30 17:36

import ckeditor.fields
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200630_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('age', models.CharField(max_length=150, verbose_name='Возраст')),
                ('technology_stack', models.TextField(blank=True, verbose_name='Стэк технологий')),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.get_timestamp_path, verbose_name='Изображение')),
                ('info', ckeditor.fields.RichTextField(blank=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Про меня',
            },
        ),
    ]
